export const defaultSchedulerConfig = {
  treeEnabled: true,
  treeAnimation: false,
  scale: 'CellDuration',
  cellDuration: 60,
  cellWidth: 64,
  sortDirections: ['asc'],
  durationBarVisible: false,
  rowHeaderWidthAutoFit: false,
  snapToGrid: false,
  locale: 'ru-ru',
  useEventBoxes: 'Never',
  heightSpec: 'Parent100Pct',
  eventClickHandling: 'Select',
  allowMultiSelect: true,
  timeRangeDoubleClickHandling: 'Disabled',
  timeRangeSelectedHandling: 'Disabled',
  eventDoubleClickHandling: 'Disabled',
  rowMarginTop: 4,
  rowMarginBottom: 4,
  floatingEvents: false,
  floatingTimeHeaders: true,
  dynamicLoading: true,
  crosshairType: 'Disabled',
  headerHeight: 40,
  rowHeaderWidth: 300,
  dynamicEventRendering: 'Progressive',
  scrollDelayCells: 200,
  timeHeaders: [{ groupBy: 'Cell', format: 'HH:mm' }],
    eventMoveHandling: 'Update',
    eventResizeHandling: 'Update',
};